<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxdelBS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxdelBS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOxdelBS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOxdelBS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOxdelBS\App_KernelDevDebugContainer([
    'container.build_hash' => 'OxdelBS',
    'container.build_id' => '80760ed5',
    'container.build_time' => 1613038149,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxdelBS');
